name: shopcom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  icons_plus: 5.0.0
  carousel_slider: 4.2.1
  flutter_product_carousel: 0.0.4
  readmore: 3.0.0
  rating_summary: 1.0.2+1
  google_fonts: 6.2.1
  flutter: 
    sdk: flutter
  dotted_line: ^3.2.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

